apiVersion: v1
kind: Pod
metadata:
  name: secret-test-pod
spec:
  containers:
    - name: test-container
      image: nginx
      env:
        - name: USERNAME
          valueFrom:
            secretKeyRef:
              name: nginx-data
              key: admin
        - name: PASSWORD
          valueFrom:
            secretKeyRef:
              name: nginx-data
              key: password
