apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-dynamic-pvc
spec:
  accessModes:
    - ReadWriteMany # EFS supports read-write by multiple nodes
  resources:
    requests:
      storage: 5Gi # Request for 5 GiB of storage
  storageClassName: efs-sc # Reference to the EFS StorageClass
